wallpaper {
	monitor = eDP-1
	path = ~/HDD/Pictures/Wallpapers/slayers_club.jpg
	fit_mode = cover
}

wallpaper {
	monitor = HDMI-A-1
	path = ~/HDD/Pictures/Wallpapers/slayers_club.jpg
	fit_mode = cover
}

splash = false
